export const dummyItems = [
  { id: 1, name: "Office A", description: "Main office" },
  { id: 2, name: "Office B", description: "Branch office" },
  { id: 3, name: "Office C", description: "Regional office" },
  { id: 4, name: "Office D", description: "Headquarters" },
  { id: 5, name: "Office E", description: "Support center" },
  { id: 6, name: "Office F", description: "Sales office" },
  { id: 7, name: "Office G", description: "HR department office" },
  { id: 8, name: "Office H", description: "Finance office" },
  { id: 9, name: "Office I", description: "IT operations office" },
  { id: 10, name: "Office J", description: "Logistics office" }
];

export const rows = [
  {
    id: 1,
    date: "24 Dec 2025",
    parcel: 15,
    type: "Inward",
    from: "Office A",
    to: "HR Dept",
    status: "Closed",
  },
  {
    id: 2,
    date: "24 Dec 2025",
    parcel: 16,
    type: "Outward",
    from: "HR Dept",
    to: "Office B",
    status: "In Transit",
  },
  {
    id: 3,
    date: "23 Dec 2025",
    parcel: 12,
    type: "Inward",
    from: "Branch X",
    to: "Accounts",
    status: "Pending",
  },
  {
    id: 4,
    date: "23 Dec 2025",
    parcel: 10,
    type: "Outward",
    from: "Accounts",
    to: "Branch X",
    status: "Closed",
  },
  {
    id: 5,
    date: "22 Dec 2025",
    parcel: 9,
    type: "Inward",
    from: "Office C",
    to: "Legal",
    status: "Under Review",
  },
  {
    id: 6,
    date: "22 Dec 2025",
    parcel: 7,
    type: "Outward",
    from: "Legal",
    to: "Office C",
    status: "Closed",
  },
];

